appiumURL=http://127.0.0.1:4723/wd/hub
androidAutomationName=UiAutomator2
androidAppLocation=/app/IDA-5.0-PATHQA
androidAppPackage=org.intelehealth.app
androidAppActivity=org.intelehealth.app.ui.splash.activity.SplashActivity
